alias sqldeveloper='~/utils/sqldeveloper/sqldeveloper.sh'
alias setkey='~/.config/startupscripts/setkeyboard'
alias libreoffice='libreoffice6.3'
alias gimp='flatpak run org.gimp.GIMP'
alias noext='~/.screenlayout/noexttern.sh'
alias siext='~/.screenlayout/singleextern.sh'
alias doma='~/.screenlayout/domasingleexter.sh'
alias nomacs='flatpak run org.nomacs.ImageLounge'
# alias teams='flatpak run com.github.IsmaelMartinez.teams_for_linux'
alias postman='~/bin/postman'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias anyconnect='/opt/cisco/anyconnect/bin/vpnui'
alias krita='flatpak run org.kde.krita'
alias evolution='flatpak run org.gnome.Evolution'
alias xin="xinput --disable $(xinput list --id-only "Synaptics TM3276-022")"
alias viq="urxvt -e vim"
alias dropbox="dropbox.py start"
