# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

import = [
    "~/.config/alacritty/themes/themes/enfocado_light.toml"
]

#fc-list : family | sort -f | grep Nerd

[font.bold]
#family = "jetbrainsmono nf"
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
#family = "jetbrainsmono nf"
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
#family = "jetbrainsmono nf"
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
#family = "jetbrainsmono nf"
family = "Hack Nerd Font Mono"
style = "Regular"

[font]
size = 16.0
# defaults write -g AppleFontSmoothing -int 0
# The use_thin_strokes config field has been removed as discussed above.
# If you still want smoothing (read: slightly bolder fonts) for the rest of the system, but not in Alacritty, you can do org.alacritty instead of -g in the above command.


[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [shell]
# args = ["new", "-A", "-s main"]
# program = "tmux"

[window]
dynamic_padding = false
opacity = 1.0

# [window.dimensions]
# columns = 250
# lines = 70

[window.padding]
x = 2
y = 0

[[keyboard.bindings]]
chars = "~"
key = "±"
mods = "Shift"

[[keyboard.bindings]]
chars = "`"
key = "§"

# [[keyboard.bindings]]
# chars = "\u001B[D"
# key = "Left"
# mode = "~AppCursor"
